server:
  port: 9000

spring:
  application:
    name: "cards"
#  profiles:
#    active: "prod"

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

#  config:
#    import: "optional:configserver:http://localhost:8071/" # O optional indica que se a conexão não der certo, que pode
#    # iniciar o projeto normalmente, pois essas configurações não afetará em nada o funcionamento.
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"