spring:
  application:
    name: accounts

#  profiles:
#    active: "prod"

  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

#  config:
#    import: "optional:configserver:http://localhost:8071/" # O optional indica que se a conexão não der certo, que pode
#    # iniciar o projeto normalmente, pois essas configurações não afetará em nada o funcionamento.
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"